safe:        false
port:        4000
url:         https://joshuacol.es
source:      .
destination: ./_site
plugins_dir: ./_plugins
comments: true

title: Joshua Cole's Personal Website
description:
  This is Joshua Cole's personal website. Among other things, I write 
  here about software engineering, machine learning, competitive
  gaming, and game theory.

future:      true
lsi:         false
highlighter: rouge


permalink:   date

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll/scholar


markdown: kramdown


author: joshuacole

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  parse_block_html: false
  parse_span_html: false
